### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by kessler1223q** [Ac-Srikanth/billing-app#1]
Hello,

I did not find any other way to contact you and I decided to write a message here.
It is regarding an older project of yours, called NasaAPI-react. I am a student currently learning about ReactJS and I noticed that on your published page, you have a collection of APOD rendered and in the version that I cloned, it does not appear for me. I found out about backendless and after some digging around I couldn't understand how you made it work. I figured the code was incomplete, but I am very invested into the project that I had to write to you.

Thank you if you read this, you'll make a student very happy if you let me know some details (unless they are private) and I will remove this Issue as soon as possible!

**Comment by Ac-Srikanth** [comment]
I am not the one who has written this, i had forked it .
